using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using AutocompleteMenuNS;
using Microsoft.Extensions.AI;
using OpenAI.Chat;
using ChatMessage = Microsoft.Extensions.AI.ChatMessage;

namespace MarkMpn.Sql4Cds.XTB
{
    internal class AIAutocomplete
    {
        private readonly SqlQueryControl _control;
        private readonly List<ChatMessage> _messages;
        private IChatClient _chatClient;
        private ChatOptions _chatOptions;

        public AIAutocomplete(SqlQueryControl control)
        {
            _control = control;
            _messages = new List<ChatMessage>();

            string systemPrompt;

            using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("MarkMpn.Sql4Cds.XTB.Resources.AIAutocompleteInstructions.txt"))
            using (var reader = new StreamReader(stream))
            {
                systemPrompt = reader.ReadToEnd();
            }

            _messages.Add(new ChatMessage(ChatRole.System, systemPrompt));
        }

        public IEnumerable<AutocompleteItem> GetSuggestions(string text, int pos)
        {
#pragma warning disable OPENAI001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
            if (_chatClient == null)
                _chatClient = Settings.Instance.CreateChatClient(builder => builder.UseFunctionInvocation());

            if (_chatOptions == null)
            {
                _chatOptions = new ChatOptions();
                _chatOptions.RawRepresentationFactory = _ => new ChatCompletionOptions { ReasoningEffortLevel = ChatReasoningEffortLevel.Low };

                var aiFunctions = new AIFunctions(_control);
                _chatOptions.Tools = new List<AITool>(aiFunctions.GetTools());
            }

            var prompt = text.Insert(pos + 1, "|");

            // Check if any of the previous messages also include this prompt
            ChatMessage response = null;

            for (var i = 0; i < _messages.Count; i++)
            {
                if (_messages[i].Role == ChatRole.User && ((TextContent)_messages[i].Contents[0]).Text == prompt)
                {
                    response = _messages[i + 1];
                    break;
                }
            }

            if (response == null)
            {
                _messages.Add(new ChatMessage(ChatRole.User, prompt));
                response = Task.Run(async () => _chatClient.GetResponseAsync(_messages, _chatOptions)).Unwrap().ConfigureAwait(false).GetAwaiter().GetResult().Messages.Last();
                _messages.Add(response);
            }

            var suggestion = response.Contents.OfType<TextContent>().Where(t => !String.IsNullOrWhiteSpace(t.Text)).FirstOrDefault();

            if (suggestion != null)
            {
                string lastSuggestion = null;

                using (var reader = new StringReader(suggestion.Text))
                {
                    string line;
                    while ((line = reader.ReadLine()) != null)
                    {
                        if (line.Length == 0)
                            continue;

                        if (line.StartsWith("- "))
                        {
                            if (lastSuggestion != null)
                                yield return new AIAutocompleteItem(lastSuggestion);

                            lastSuggestion = null;
                        }

                        if (lastSuggestion == null)
                            lastSuggestion = line.Substring(2);
                        else if (line.StartsWith("  "))
                            lastSuggestion += "\r\n" + line.Substring(2);
                        else
                            lastSuggestion += "\r\n" + line;
                    }
                }

                if (lastSuggestion != null)
                    yield return new AIAutocompleteItem(lastSuggestion);
            }
#pragma warning restore OPENAI001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
        }

        class AIAutocompleteItem : AutocompleteItem
        {
            public AIAutocompleteItem(string text) : base(text, 27)
            {
            }

            public override string MenuText
            {
                get => Text.Replace("\r\n", " ").Replace("\r", " ").Replace("\n", " ");
                set { }
            }

            public override string ToolTipTitle
            {
                get => "AI Suggestion";
                set { }
            }

            public override string ToolTipText
            {
                get => "This suggestion was generated by AI, review it carefully before use";
                set { }
            }
        }
    }
}
