using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace xrmtb.XrmToolBox.Controls
{
    /// <summary>
    /// The data format of the JSON document generated by <see cref="EntityCollectionSerializer.ToJSON(Microsoft.Xrm.Sdk.EntityCollection, System.Xml.Formatting, JsonFormat)"/>
    /// and <see cref="EntitySerializer.ToJSONObject(Microsoft.Xrm.Sdk.Entity, JsonFormat)"/>
    /// </summary>
    public enum JsonFormat
    {
        /// <summary>
        /// The original JSON format that has been produced historically
        /// </summary>
        Legacy,

        /// <summary>
        /// A JSON format closer to that produced by WebAPI
        /// </summary>
        WebApi
    }
}
