import { randomBytes } from "node:crypto";
import type * as vscode from "vscode";

/** Builds the self-contained results grid webview. Grid state deliberately lives in
 * the webview so paging only renders a small window while selection can span the
 * complete transformed result. */
export function resultsHtml(webview: vscode.Webview): string {
  const nonce = createNonce();
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource} 'nonce-${nonce}'; script-src 'nonce-${nonce}';">
  <style nonce="${nonce}">
    :root{color-scheme:light dark}*{box-sizing:border-box}body{height:100vh;margin:0;overflow:hidden;font-family:var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-editor-background)}button,input,select{font:inherit;color:inherit}
    .tabs{display:flex;gap:2px;overflow:auto;height:36px;padding:4px 8px 0;border-bottom:1px solid var(--vscode-panel-border)}.tabs:empty{display:none}.tabs:empty+main{height:100vh}.tab{cursor:pointer;color:var(--vscode-foreground);background:transparent;border:0;border-bottom:2px solid transparent;padding:4px 10px}.tab:hover{background:var(--vscode-toolbar-hoverBackground)}.tab.active{border-bottom-color:var(--vscode-focusBorder);font-weight:600}
    main{height:calc(100vh - 36px);padding:6px 8px}.toolbar{display:flex;align-items:center;min-height:30px;gap:4px;margin-bottom:4px}.toolbar .meta{min-width:90px;color:var(--vscode-descriptionForeground);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.search{display:flex;align-items:center;min-width:150px;max-width:300px;flex:1;margin-right:auto}.search input{min-width:0;width:100%;height:25px;padding:2px 24px 2px 7px;border:1px solid var(--vscode-input-border,transparent);background:var(--vscode-input-background);color:var(--vscode-input-foreground)}.search .clear{width:22px;height:22px;margin-left:-23px;border:0;background:transparent;cursor:pointer}.search .clear:hover{background:var(--vscode-toolbar-hoverBackground)}.page-label,.selection-status{padding:0 4px;color:var(--vscode-descriptionForeground);font-variant-numeric:tabular-nums;white-space:nowrap}.selection-status{margin-left:4px}
    .icon-button{display:grid;place-items:center;width:26px;height:26px;padding:0;color:var(--vscode-foreground);background:transparent;border:0;border-radius:3px;font-size:16px;line-height:1;cursor:pointer}.icon-button:hover:not(:disabled),.header-button:hover{background:var(--vscode-toolbar-hoverBackground)}.icon-button:disabled{opacity:.35;cursor:default}.tab:focus-visible,.icon-button:focus-visible,.header-button:focus-visible,.grid:focus-visible{outline:1px solid var(--vscode-focusBorder);outline-offset:-1px}
    .result-area{display:flex;min-width:0;height:calc(100% - 34px)}.grid{min-width:0;flex:1;overflow:auto;border-top:1px solid var(--vscode-panel-border);border-left:1px solid var(--vscode-panel-border);outline:none}.grid-actions{display:flex;flex:0 0 32px;flex-direction:column;align-items:center;gap:2px;padding:2px 3px;border-left:1px solid var(--vscode-panel-border)}
    table{border-collapse:separate;border-spacing:0;min-width:100%;table-layout:fixed;font-family:var(--vscode-editor-font-family);font-size:var(--vscode-editor-font-size)}th,td{height:26px;padding:3px 7px;border-right:1px solid var(--vscode-panel-border);border-bottom:1px solid var(--vscode-panel-border);text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:middle}th{position:sticky;top:0;z-index:3;padding:0;min-width:90px;background:var(--vscode-editorGroupHeader-tabsBackground);user-select:none}.corner,.row-gutter{position:sticky;left:0;z-index:4;width:52px;min-width:52px;max-width:52px;text-align:right;background:var(--vscode-editorGroupHeader-tabsBackground);color:var(--vscode-descriptionForeground);font-variant-numeric:tabular-nums;cursor:pointer}.corner{z-index:5;text-align:center}.header{display:flex;align-items:stretch;height:25px}.header-button{height:25px;padding:2px 5px;border:0;background:transparent;cursor:pointer}.drag-handle{width:19px;padding:2px;color:var(--vscode-descriptionForeground);cursor:grab}.column-name{min-width:0;flex:1;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sort.active,.filter.active{color:var(--vscode-textLink-foreground);background:var(--vscode-toolbar-activeBackground)}.resize-handle{position:absolute;right:-2px;top:0;z-index:8;width:5px;height:100%;cursor:col-resize}td{cursor:cell}.null{color:var(--vscode-descriptionForeground);font-style:italic}td.structured{position:relative;padding-right:25px;text-decoration:underline;text-decoration-style:dotted;text-decoration-color:var(--vscode-textLink-foreground)}td.structured::after{content:'↗';position:absolute;right:6px;color:var(--vscode-textLink-foreground);font-family:var(--vscode-font-family);font-style:normal}.selected{background:var(--vscode-list-activeSelectionBackground)!important;color:var(--vscode-list-activeSelectionForeground)!important}.focused{outline:1px solid var(--vscode-focusBorder);outline-offset:-2px}.column-drag{opacity:.55}
    td.structured{cursor:pointer}
    .popover,.context-menu{position:fixed;z-index:20;min-width:210px;padding:6px;background:var(--vscode-menu-background,var(--vscode-editorWidget-background));color:var(--vscode-menu-foreground,var(--vscode-foreground));border:1px solid var(--vscode-menu-border,var(--vscode-widget-border));box-shadow:0 2px 8px var(--vscode-widget-shadow);border-radius:3px}.popover{display:grid;gap:6px}.popover label{font-size:.9em;color:var(--vscode-descriptionForeground)}.popover select,.popover input{width:100%;height:26px;border:1px solid var(--vscode-input-border,transparent);background:var(--vscode-input-background);color:var(--vscode-input-foreground)}.popover-actions{display:flex;justify-content:flex-end;gap:5px}.popover-actions button{cursor:pointer}.context-menu{padding:4px;min-width:190px}.menu-item{display:block;width:100%;padding:5px 9px;border:0;text-align:left;background:transparent;cursor:pointer}.menu-item:hover{background:var(--vscode-menu-selectionBackground);color:var(--vscode-menu-selectionForeground)}.menu-separator{height:1px;margin:3px 5px;background:var(--vscode-menu-separatorBackground,var(--vscode-panel-border))}
    .empty,.error{padding:20px;color:var(--vscode-descriptionForeground)}.error,.message.error{color:var(--vscode-errorForeground)}.messages{height:100%;margin:0;padding:0;overflow:auto;list-style:none}.message{padding:7px 9px;border-bottom:1px solid var(--vscode-panel-border);white-space:pre-wrap}.message time{display:block;margin-bottom:2px;color:var(--vscode-descriptionForeground);font-size:.9em}
  </style>
</head>
<body>
  <nav id="tabs" class="tabs" aria-label="Query results"></nav><main id="content"><div class="empty">Waiting for query results…</div></main>
  <script nonce="${nonce}">
    const vscode = acquireVsCodeApi();
    const tabs = document.getElementById('tabs');
    const content = document.getElementById('content');
    let state, active, currentPage = 0, currentPageData, userSelectedTab = false, dragSelecting = false, searchTimer, restoreGridFocus = false, restoreSearchFocus = false;
    const pages = new Map(), pending = new Set(), views = new Map();

    function freshView(result) { return { searchText:'', filters:new Map(), sort:undefined, viewVersion:0, columnOrder:result.columns.map((_,i)=>i), widths:new Map(), terms:[], anchor:undefined, focus:undefined }; }
    function viewFor(result) { let view=views.get(result.key); if(!view){view=freshView(result);views.set(result.key,view);} return view; }
    function spec(view){ return {searchText:view.searchText,filters:[...view.filters].map(([columnIndex,f])=>({columnIndex,operator:f.operator,value:f.value})),sort:view.sort,viewVersion:view.viewVersion}; }
    function invalidate(result, clearSelection){ const view=viewFor(result); restoreSearchFocus=document.activeElement?.matches('.search input')||false; view.viewVersion++; if(clearSelection){view.terms=[];view.anchor=undefined;view.focus=undefined;} currentPage=0;currentPageData=undefined; const prefix=state.runId+':'+result.key+':';for(const key of [...pages.keys()])if(key.startsWith(prefix))pages.delete(key);for(const key of [...pending])if(key.startsWith(prefix))pending.delete(key);showActive(); }

    window.addEventListener('message', event => {
      const message=event.data;
      if(message.type==='state'){
        const changedRun=!state||state.runId!==message.runId; state=message;
        if(changedRun){clearTimeout(searchTimer);restoreGridFocus=false;restoreSearchFocus=false;pages.clear();pending.clear();views.clear();active='messages';userSelectedTab=false;currentPage=0;currentPageData=undefined;}
        renderState();
      }else if(message.type==='empty'){
        clearTimeout(searchTimer);restoreGridFocus=false;restoreSearchFocus=false;state=undefined;active=undefined;userSelectedTab=false;pages.clear();pending.clear();views.clear();dismissOverlays();tabs.replaceChildren();content.replaceChildren(makeNode('div','empty','Run a query to see its results.'));
      }else if(message.type==='page'&&state&&message.runId===state.runId){
        const result=state.results.find(x=>x.key===message.key); if(!result)return; const view=viewFor(result);
        const responseVersion=message.viewVersion??view.viewVersion,cacheKey=pageKey(message.key,message.page,responseVersion);pending.delete(cacheKey);
        if(responseVersion!==view.viewVersion)return;
        pages.set(cacheKey,message);while(pages.size>3)pages.delete(pages.keys().next().value);
        if(active===message.key&&currentPage===message.page)renderResult();
      }else if(message.type==='pageError'&&state&&message.runId===state.runId){
        const result=state.results.find(x=>x.key===message.key);if(!result)return;const view=viewFor(result),responseVersion=message.viewVersion??view.viewVersion;pending.delete(pageKey(message.key,message.page,responseVersion));if(responseVersion!==view.viewVersion)return;
        if(active===message.key&&currentPage===message.page)showError(message.message);
      }
    });
    window.addEventListener('pointerup',()=>dragSelecting=false);
    window.addEventListener('blur',()=>{dragSelecting=false;dismissOverlays();});
    document.addEventListener('pointerdown',event=>{if(!event.target.closest('.popover,.context-menu,.filter'))dismissOverlays();});
    document.addEventListener('keydown',event=>{if(event.key==='Escape')dismissOverlays();});

    function renderState(){
      tabs.replaceChildren();for(const result of state.results)addTab(result.key,state.results.length===1?'Results':'Result '+result.ordinal);addTab('messages','Messages'+(state.messages.length?' ('+state.messages.length+')':''));
      const errors=state.status==='failed'||state.messages.some(x=>x.isError);if(errors){active='messages';userSelectedTab=false;}else if(!state.results.length){active='messages';}else if(active==='messages'&&!userSelectedTab){active=state.results[0].key;}else if(!active||(active!=='messages'&&!state.results.some(x=>x.key===active))){active=state.results[0].key;}
      for(const tab of tabs.children)tab.classList.toggle('active',tab.dataset.key===active);showActive();
    }
    function addTab(key,label){const b=makeNode('button','tab',label);b.dataset.key=key;b.setAttribute('role','tab');b.addEventListener('click',()=>{clearTimeout(searchTimer);restoreSearchFocus=false;restoreGridFocus=false;active=key;userSelectedTab=true;currentPage=0;dismissOverlays();for(const tab of tabs.children)tab.classList.toggle('active',tab.dataset.key===active);showActive();});tabs.append(b);}
    function showActive(){
      dismissOverlays();if(active==='messages'){renderMessages();return;}const result=state.results.find(x=>x.key===active);
      if(!result){content.replaceChildren(makeNode('div','empty',state.status==='running'||state.status==='cancelling'?'Waiting for query results…':'No result sets were returned.'));return;}
      if(!result.complete){content.replaceChildren(makeNode('div','empty','Waiting for this result set to finish…'));return;}
      const view=viewFor(result), known=currentPageData&&currentPageData.key===active?currentPageData.displayRows:result.displayRowCount;const last=Math.max(0,Math.ceil(known/result.pageSize)-1);currentPage=Math.min(currentPage,last);
      const cached=pages.get(pageKey(active,currentPage,view.viewVersion));if(cached){renderResult();return;}const loading=makeNode('div','empty','Loading result page…');const area=content.querySelector('.result-area');if(restoreSearchFocus&&area)area.replaceChildren(loading);else content.replaceChildren(loading);requestPage(result);
    }
    function requestPage(result){const view=viewFor(result),key=pageKey(result.key,currentPage,view.viewVersion);if(pending.has(key))return;pending.add(key);vscode.postMessage({type:'page',ownerUri:state.ownerUri,runId:state.runId,key:result.key,page:currentPage,...spec(view)});}

    function renderResult(){
      const result=state.results.find(x=>x.key===active);if(!result)return;const view=viewFor(result),page=pages.get(pageKey(active,currentPage,view.viewVersion));if(!page)return;currentPageData={...page,key:active};const focused=document.activeElement;const keepGrid=restoreGridFocus||focused?.classList.contains('grid');const keepSearch=restoreSearchFocus||focused?.matches('.search input');const oldGrid=content.querySelector('.grid');const scrollLeft=oldGrid?.scrollLeft||0,scrollTop=oldGrid?.scrollTop||0;content.replaceChildren();
      const toolbar=makeNode('div','toolbar');const search=makeNode('div','search');const input=document.createElement('input');input.type='search';input.placeholder='Search all columns';input.setAttribute('aria-label','Quick search results');input.value=keepSearch&&focused?.matches('.search input')?focused.value:view.searchText;input.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(view.searchText===input.value)return;view.searchText=input.value;invalidate(result,true);},250);});const clear=makeNode('button','clear','×');clear.title='Clear search';clear.addEventListener('click',()=>{input.value='';if(view.searchText){view.searchText='';invalidate(result,true);}});search.append(input,clear);toolbar.append(search);
      const first=page.displayRows?page.start+1:0,lastRow=page.start+page.rows.length;const originalTotal=page.totalRows??result.rowCount,filteredTotal=page.filteredRows??page.displayRows,transformed=page.displayRows,isFiltered=filteredTotal!==originalTotal;
      const detail=page.truncated?first.toLocaleString()+'–'+lastRow.toLocaleString()+' of '+transformed.toLocaleString()+' displayed ('+(isFiltered?filteredTotal.toLocaleString()+' matching; ':'')+originalTotal.toLocaleString()+' total; display limit reached)':first.toLocaleString()+'–'+lastRow.toLocaleString()+' of '+transformed.toLocaleString()+(isFiltered?' matching ('+originalTotal.toLocaleString()+' total)':'');toolbar.append(makeNode('span','meta',detail));
      const lastPage=Math.max(0,Math.ceil(transformed/result.pageSize)-1);toolbar.append(iconButton('First page','⇤',()=>changePage(0),currentPage===0),iconButton('Previous page','‹',()=>changePage(currentPage-1),currentPage===0),makeNode('span','page-label',(currentPage+1)+' / '+(lastPage+1)),iconButton('Next page','›',()=>changePage(currentPage+1),currentPage>=lastPage),iconButton('Last page','⇥',()=>changePage(lastPage),currentPage>=lastPage));
      const selectionLabel=selectionSummary(view,result,transformed);toolbar.append(makeNode('span','selection-status',selectionLabel));if(view.searchText||view.filters.size||view.sort)toolbar.append(iconButton('Clear search, filters and sort','↺',()=>{view.searchText='';view.filters.clear();view.sort=undefined;invalidate(result,true);},false));content.append(toolbar);
      if(!result.columns.length){content.append(makeNode('div','empty','This result set has no columns.'));return;}
      const area=makeNode('div','result-area'),grid=makeNode('div','grid');grid.tabIndex=0;grid.setAttribute('role','grid');grid.setAttribute('aria-rowcount',String(transformed+1));grid.setAttribute('aria-colcount',String(result.columns.length+1));grid.addEventListener('keydown',event=>gridKeyDown(event,result,page,view));grid.addEventListener('pointerdown',()=>grid.focus({preventScroll:true}));
      const table=document.createElement('table'),thead=document.createElement('thead'),hr=document.createElement('tr'),corner=makeNode('th','corner','◩');corner.title='Select all filtered results';corner.addEventListener('click',event=>{if(transformed>0)selectArea(view,0,transformed-1,view.columnOrder,event,false);});hr.append(corner);
      for(const originalIndex of view.columnOrder)hr.append(makeHeader(result,view,originalIndex,transformed));thead.append(hr);table.append(thead);const tbody=document.createElement('tbody');
      page.rows.forEach((row,localRow)=>{const logicalRow=page.start+localRow,tr=document.createElement('tr'),gutter=makeNode('th','row-gutter',String(logicalRow+1));gutter.scope='row';gutter.addEventListener('pointerdown',event=>{if(event.button!==0)return;selectArea(view,logicalRow,logicalRow,view.columnOrder,event,true);dragSelecting=true;});gutter.addEventListener('pointerenter',event=>{if(dragSelecting&&(event.buttons&1))extendArea(view,logicalRow,view.columnOrder);});gutter.addEventListener('contextmenu',event=>openContext(event,result,view,logicalRow,undefined));tr.append(gutter);
        view.columnOrder.forEach((originalIndex,visualColumn)=>{const value=originalIndex<row.length?row[originalIndex]:null,candidate=isStructuredCandidate(value),td=makeNode('td',(value===null?'null':'')+(candidate?' structured':''),value===null?'NULL':value);td.dataset.row=String(logicalRow);td.dataset.column=String(originalIndex);td.title=candidate?'Double-click to view formatted value':value===null?'NULL':String(value);decorateCell(td,view,logicalRow,originalIndex);td.addEventListener('pointerdown',event=>{if(event.button!==0)return;selectArea(view,logicalRow,logicalRow,[originalIndex],event,true);dragSelecting=true;});td.addEventListener('pointerenter',event=>{if(dragSelecting&&(event.buttons&1))extendCell(view,logicalRow,originalIndex);});if(candidate)td.addEventListener('dblclick',()=>vscode.postMessage({type:'viewCell',ownerUri:state.ownerUri,runId:state.runId,key:active,row:logicalRow,columnIndex:originalIndex,text:value,...spec(view)}));td.addEventListener('contextmenu',event=>openContext(event,result,view,logicalRow,originalIndex));tr.append(td);});tbody.append(tr);});
      table.append(tbody);grid.append(table);area.append(grid);const actions=makeNode('aside','grid-actions');actions.setAttribute('aria-label','Result actions');actions.append(iconButton('Copy selection','⧉',()=>copySelection(result,view,'tsv',false),!view.terms.length),iconButton('Copy selection with headers','⧉⁺',()=>copySelection(result,view,'tsv',true),!view.terms.length),iconButton('Export full result set…','⇩',()=>vscode.postMessage({type:'export',ownerUri:state.ownerUri,runId:state.runId,key:active}),!result.complete));area.append(actions);content.append(area);grid.scrollLeft=scrollLeft;grid.scrollTop=scrollTop;if(keepSearch)input.focus({preventScroll:true});else if(keepGrid)grid.focus({preventScroll:true});restoreGridFocus=false;restoreSearchFocus=false;paintSelection(view);
    }

    function makeHeader(result,view,columnIndex,rowCount){
      const th=document.createElement('th');th.dataset.column=String(columnIndex);const width=view.widths.get(columnIndex);if(width)th.style.width=width+'px';const box=makeNode('div','header');const drag=makeNode('button','header-button drag-handle','⋮⋮');drag.title='Drag to reorder column';drag.draggable=true;drag.addEventListener('dragstart',event=>{event.dataTransfer.setData('text/plain',String(columnIndex));th.classList.add('column-drag');});drag.addEventListener('dragend',()=>th.classList.remove('column-drag'));th.addEventListener('dragover',event=>event.preventDefault());th.addEventListener('drop',event=>{event.preventDefault();const from=Number(event.dataTransfer.getData('text/plain')),to=view.columnOrder.indexOf(columnIndex);if(!Number.isInteger(from)||from===columnIndex)return;const old=view.columnOrder.indexOf(from);if(old<0)return;view.columnOrder.splice(old,1);view.columnOrder.splice(to,0,from);renderResult();});
      const name=makeNode('button','header-button column-name',result.columns[columnIndex]||'(unnamed)');name.title='Select column '+(result.columns[columnIndex]||columnIndex+1);name.addEventListener('click',event=>{if(rowCount>0)selectArea(view,0,rowCount-1,[columnIndex],event,false);});
      const direction=view.sort&&view.sort.columnIndex===columnIndex?view.sort.direction:undefined,sort=makeNode('button','header-button sort'+(direction?' active':''),direction==='asc'?'↑':direction==='desc'?'↓':'↕');sort.title=direction?'Sorted '+direction+'. Click to change.':'Sort column';sort.addEventListener('click',event=>{event.stopPropagation();view.sort=!direction?{columnIndex,direction:'asc'}:direction==='asc'?{columnIndex,direction:'desc'}:undefined;invalidate(result,true);});
      const filter=makeNode('button','header-button filter'+(view.filters.has(columnIndex)?' active':''),'⌄');filter.title='Filter column';filter.addEventListener('click',event=>{event.stopPropagation();openFilter(event,result,view,columnIndex);});box.append(drag,name,sort,filter);th.append(box);const resize=makeNode('span','resize-handle');resize.addEventListener('pointerdown',event=>startResize(event,th,view,columnIndex));th.append(resize);return th;
    }
    function startResize(event,th,view,column){event.preventDefault();event.stopPropagation();const start=event.clientX,width=th.getBoundingClientRect().width;function move(e){const next=Math.max(52,width+e.clientX-start);th.style.width=next+'px';view.widths.set(column,next);}function up(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);}
    function openFilter(event,result,view,columnIndex){dismissOverlays();const current=view.filters.get(columnIndex)||{operator:'contains',value:''},pop=makeNode('div','popover');pop.style.left=Math.max(4,Math.min(event.clientX,window.innerWidth-225))+'px';pop.style.top=Math.max(4,Math.min(event.clientY+18,window.innerHeight-145))+'px';pop.append(makeNode('label','',result.columns[columnIndex]||'Column '+(columnIndex+1)));const select=document.createElement('select');[['contains','Contains'],['equals','Equals'],['notEquals','Does not equal'],['startsWith','Starts with'],['endsWith','Ends with'],['greaterThan','Greater than'],['greaterThanOrEqual','Greater than or equal'],['lessThan','Less than'],['lessThanOrEqual','Less than or equal'],['isEmpty','Is empty'],['isNotEmpty','Is not empty']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;select.append(o);});select.value=current.operator;const input=document.createElement('input');input.placeholder='Filter value';input.value=current.value;const updateDisabled=()=>input.disabled=select.value==='isEmpty'||select.value==='isNotEmpty';select.addEventListener('change',updateDisabled);updateDisabled();const buttons=makeNode('div','popover-actions'),clear=makeNode('button','','Clear'),apply=makeNode('button','','Apply');clear.addEventListener('click',()=>{view.filters.delete(columnIndex);dismissOverlays();invalidate(result,true);});apply.addEventListener('click',()=>{view.filters.set(columnIndex,{operator:select.value,value:input.value});dismissOverlays();invalidate(result,true);});input.addEventListener('keydown',e=>{if(e.key==='Enter')apply.click();});buttons.append(clear,apply);pop.append(select,input,buttons);document.body.append(pop);input.focus();}

    function selectArea(view,rowStart,rowEnd,columnIds,event,setAnchor){
      const additive=event.metaKey||event.ctrlKey;if(event.shiftKey&&view.anchor){view.terms=additive?view.terms:[];addTerm(view,view.anchor.row,rowEnd,columnsBetween(view,view.anchor.column,columnIds[columnIds.length-1]),true);}else{let selected=true;for(let row=rowStart;selected&&row<=rowEnd;row++)for(const column of columnIds)if(!isSelected(view,row,column)){selected=false;break;}if(!additive)view.terms=[];addTerm(view,rowStart,rowEnd,columnIds,!(additive&&selected));if(setAnchor||!view.anchor)view.anchor={row:rowStart,column:columnIds[0]};}view.focus={row:rowEnd,column:columnIds[columnIds.length-1]};paintSelection(view);
    }
    function extendArea(view,row,columnIds){if(!view.anchor)return;view.terms=view.terms.filter(x=>!x.preview);const term=addTerm(view,view.anchor.row,row,columnsBetween(view,view.anchor.column,columnIds[columnIds.length-1]),true);term.preview=true;view.focus={row,column:columnIds[columnIds.length-1]};paintSelection(view);}
    function extendCell(view,row,column){extendArea(view,row,[column]);}
    function addTerm(view,r1,r2,columnIds,selected){const term={rowStart:Math.min(r1,r2),rowEnd:Math.max(r1,r2),columnIds:[...new Set(columnIds)],selected};view.terms.push(term);return term;}
    function columnsBetween(view,a,b){const ai=view.columnOrder.indexOf(a),bi=view.columnOrder.indexOf(b);return view.columnOrder.slice(Math.min(ai,bi),Math.max(ai,bi)+1);}
    function isSelected(view,row,column){let selected=false;for(const term of view.terms)if(row>=term.rowStart&&row<=term.rowEnd&&term.columnIds.includes(column))selected=term.selected;return selected;}
    function decorateCell(cell,view,row,column){cell.classList.toggle('selected',isSelected(view,row,column));cell.classList.toggle('focused',!!view.focus&&view.focus.row===row&&view.focus.column===column);cell.setAttribute('aria-selected',String(isSelected(view,row,column)));}
    function paintSelection(view){document.querySelectorAll('td[data-row]').forEach(cell=>decorateCell(cell,view,Number(cell.dataset.row),Number(cell.dataset.column)));document.querySelectorAll('th[data-column]').forEach(header=>{const column=Number(header.dataset.column),selected=view.terms.length>0&&currentPageData&&isSelected(view,0,column)&&isSelected(view,Math.max(0,currentPageData.displayRows-1),column);header.classList.toggle('selected',!!selected);});document.querySelectorAll('.row-gutter').forEach((gutter,index)=>{const row=(currentPageData?.start||0)+index;gutter.classList.toggle('selected',view.columnOrder.every(column=>isSelected(view,row,column)));});const any=selectionRanges(view).length>0;document.querySelectorAll('.grid-actions button[title^="Copy selection"]').forEach(button=>button.disabled=!any);updateSelectionStatus(view);}
    function selectionRanges(view){
      if(!view.terms.length)return[];const boundaries=new Set();for(const t of view.terms){boundaries.add(t.rowStart);boundaries.add(t.rowEnd+1);}const rows=[...boundaries].sort((a,b)=>a-b),out=[];
      for(let i=0;i<rows.length-1;i++){const rs=rows[i],re=rows[i+1]-1;let start=-1;for(let c=0;c<=view.columnOrder.length;c++){const yes=c<view.columnOrder.length&&isSelected(view,rs,view.columnOrder[c]);if(yes&&start<0)start=c;if(!yes&&start>=0){out.push({rowStart:rs,rowEnd:re,columnStart:start,columnEnd:c-1});start=-1;}}}
      const merged=[];for(const range of out){const prior=merged.find(x=>x.columnStart===range.columnStart&&x.columnEnd===range.columnEnd&&x.rowEnd+1===range.rowStart);if(prior)prior.rowEnd=range.rowEnd;else merged.push({...range});}return merged;
    }
    function selectionSummary(view,result,rowCount){const ranges=selectionRanges(view);if(!ranges.length)return'';let cells=0,rows=new Set(),cols=new Set();for(const range of ranges){cells+=(range.rowEnd-range.rowStart+1)*(range.columnEnd-range.columnStart+1);for(let c=range.columnStart;c<=range.columnEnd;c++)cols.add(c);if(range.rowEnd-range.rowStart<10000)for(let r=range.rowStart;r<=range.rowEnd;r++)rows.add(r);}const rowText=rows.size?rows.size.toLocaleString():rowCount.toLocaleString();return rowText+' rows × '+cols.size.toLocaleString()+' columns selected ('+cells.toLocaleString()+' cells)';}
    function updateSelectionStatus(view){const result=state.results.find(x=>x.key===active),node=document.querySelector('.selection-status');if(result&&node)node.textContent=selectionSummary(view,result,currentPageData?.displayRows??result.displayRowCount);}

    function gridKeyDown(event,result,page,view){if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','a','A','c','C'].includes(event.key))return;if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='a'){event.preventDefault();if(!page.displayRows||!view.columnOrder.length)return;view.terms=[];addTerm(view,0,page.displayRows-1,view.columnOrder,true);view.focus={row:0,column:view.columnOrder[0]};view.anchor={...view.focus};paintSelection(view);return;}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='c'){event.preventDefault();copySelection(result,view,'tsv',false);return;}if(!event.key.startsWith('Arrow')||!page.displayRows||!view.columnOrder.length)return;event.preventDefault();const focus=view.focus||{row:page.start,column:view.columnOrder[0]},visual=view.columnOrder.indexOf(focus.column);let row=focus.row,column=focus.column;if(event.key==='ArrowUp')row=Math.max(0,row-1);if(event.key==='ArrowDown')row=Math.min(page.displayRows-1,row+1);if(event.key==='ArrowLeft')column=view.columnOrder[Math.max(0,visual-1)];if(event.key==='ArrowRight')column=view.columnOrder[Math.min(view.columnOrder.length-1,visual+1)];if(event.shiftKey&&view.anchor){view.terms=[];addTerm(view,view.anchor.row,row,columnsBetween(view,view.anchor.column,column),true);}else{view.terms=[];addTerm(view,row,row,[column],true);view.anchor={row,column};}view.focus={row,column};const targetPage=Math.floor(row/result.pageSize);if(targetPage!==currentPage)changePage(targetPage);else{paintSelection(view);document.querySelector('td[data-row="'+row+'"][data-column="'+column+'"]')?.scrollIntoView({block:'nearest',inline:'nearest'});}}
    function copySelection(result,view,format,headers){const ranges=selectionRanges(view);if(!ranges.length)return;vscode.postMessage({type:'copySelection',ownerUri:state.ownerUri,runId:state.runId,key:active,selection:{ranges,columnOrder:view.columnOrder},format,headers,...spec(view)});}
    function openContext(event,result,view,row,column){event.preventDefault();const rowSelected=view.columnOrder.every(id=>isSelected(view,row,id));if(column!==undefined&&!isSelected(view,row,column)){view.terms=[];addTerm(view,row,row,[column],true);view.anchor={row,column};view.focus={row,column};paintSelection(view);}else if(column===undefined&&!rowSelected){view.terms=[];addTerm(view,row,row,view.columnOrder,true);view.anchor={row,column:view.columnOrder[0]};view.focus={...view.anchor};paintSelection(view);}dismissOverlays();const menu=makeNode('div','context-menu');menu.style.left=Math.max(4,Math.min(event.clientX,window.innerWidth-205))+'px';menu.style.top=Math.max(4,Math.min(event.clientY,window.innerHeight-260))+'px';const add=(label,fn)=>{const b=makeNode('button','menu-item',label);b.addEventListener('click',()=>{dismissOverlays();fn();});menu.append(b);};add('Copy',()=>copySelection(result,view,'tsv',false));add('Copy with headers',()=>copySelection(result,view,'tsv',true));menu.append(makeNode('div','menu-separator'));add('Copy as CSV',()=>copySelection(result,view,'csv',true));add('Copy as JSON',()=>copySelection(result,view,'json',true));add('Copy as XML',()=>copySelection(result,view,'xml',true));add('Copy as Markdown',()=>copySelection(result,view,'markdown',true));add('Copy as SQL IN clause',()=>copySelection(result,view,'sqlIn',false));menu.append(makeNode('div','menu-separator'));add('Select row',()=>{view.terms=[];addTerm(view,row,row,view.columnOrder,true);renderResult();});if(column!==undefined){add('Select column',()=>{view.terms=[];addTerm(view,0,Math.max(0,currentPageData.displayRows-1),[column],true);renderResult();});const local=row-currentPageData.start,value=currentPageData.rows[local]?.[column];if(isStructuredCandidate(value))add('View formatted value',()=>vscode.postMessage({type:'viewCell',ownerUri:state.ownerUri,runId:state.runId,key:active,row,columnIndex:column,text:value,...spec(view)}));}document.body.append(menu);}
    function isStructuredCandidate(value){if(typeof value!=='string')return false;const text=value.trim();return (text.startsWith('{')&&text.endsWith('}'))||(text.startsWith('[')&&text.endsWith(']'))||text.startsWith('<');}
    function dismissOverlays(){document.querySelectorAll('.popover,.context-menu').forEach(x=>x.remove());}
    function changePage(page){restoreGridFocus=document.activeElement?.classList.contains('grid')||false;currentPage=Math.max(0,page);currentPageData=undefined;showActive();}
    function renderMessages(){content.replaceChildren();if(!state.messages.length){content.append(makeNode('div','empty',state.status==='running'?'Running query…':'No messages.'));return;}const list=makeNode('ol','messages');for(const message of state.messages){const item=makeNode('li','message'+(message.isError?' error':''));if(message.time){const time=document.createElement('time'),date=new Date(message.time);time.textContent=Number.isNaN(date.valueOf())?message.time:date.toLocaleTimeString();item.append(time);}item.append(document.createTextNode(message.message));list.append(item);}content.append(list);}
    function showError(message){content.replaceChildren(makeNode('div','error',message));}
    function iconButton(label,glyph,handler,disabled){const b=makeNode('button','icon-button',glyph);b.title=label;b.setAttribute('aria-label',label);b.disabled=disabled;b.addEventListener('click',handler);return b;}
    function makeNode(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
    function pageKey(key,page,version){return state.runId+':'+key+':'+version+':'+page;}
    vscode.postMessage({type:'ready'});
  </script>
</body>
</html>`;
}

function createNonce(): string {
  return randomBytes(32).toString("base64");
}
